using System.Numerics;
using Xunit;

namespace FNARTS.Core.Tests.Entity
{
    public class UnitTests
    {
        [Fact]
        public void Constructor_UsesDefinition()
        {
            var def = new UnitDef { Id = "marine", Name = "Marine", MoveSpeed = 80f };
            var unit = new Unit(def);
            Assert.Same(def, unit.Definition);
            Assert.Equal(80f, unit.MoveSpeed);
            Assert.True(unit.IsAlive);
        }

        [Fact]
        public void Id_IsAutoGenerated()
        {
            var def = new UnitDef();
            var u1 = new Unit(def);
            var u2 = new Unit(def);
            Assert.NotEqual(u1.Id, u2.Id);
        }

        [Fact]
        public void Update_NoTarget_DoesNothing()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(50, 50) };
            unit.Update(1f);
            Assert.Equal(new Vector2(50, 50), unit.WorldPosition);
        }

        [Fact]
        public void Update_MovesTowardTarget()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(100, 0);
            unit.Update(0.5f); // 50 pixels at 100px/s for 0.5s

            Assert.Equal(50f, unit.WorldPosition.X, 3);
            Assert.Equal(0f, unit.WorldPosition.Y, 3);
            Assert.NotNull(unit.MoveTarget); // still has target
        }

        [Fact]
        public void Update_ArrivesAtTarget()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(1.5f, 0); // within 2px
            unit.Update(0.1f);

            Assert.Equal(1.5f, unit.WorldPosition.X, 3);
            Assert.Null(unit.MoveTarget); // arrived, target cleared
        }

        [Fact]
        public void Update_SnapsToTarget_WhenOvershooting()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(10, 0);
            unit.Update(1f); // 100px step > 10px distance

            Assert.Equal(10f, unit.WorldPosition.X, 3);
            Assert.Null(unit.MoveTarget);
        }

        [Fact]
        public void Update_Dead_DoesNotMove()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0), IsAlive = false };
            unit.MoveTarget = new Vector2(100, 0);
            unit.Update(1f);

            Assert.Equal(Vector2.Zero, unit.WorldPosition);
            Assert.NotNull(unit.MoveTarget); // target not cleared
        }

        [Fact]
        public void Update_DiagonalMovement()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(100, 100);
            unit.Update(1f); // moves 100 pixels diagonal

            // Direction should be (100,100)/~141.4 normalized * 100
            Assert.Equal(70.71f, unit.WorldPosition.X, 1);
            Assert.Equal(70.71f, unit.WorldPosition.Y, 1);
        }
    }
}
