using System.Collections.Generic;
using System.Numerics;
using Xunit;

namespace FNARTS.Core.Tests.Entity
{
    public class UnitTests
    {
        [Fact]
        public void Constructor_UsesDefinition()
        {
            var def = new UnitDef { Id = "marine", Name = "Marine", MoveSpeed = 80f };
            var unit = new Unit(def);
            Assert.Same(def, unit.Definition);
            Assert.Equal(80f, unit.MoveSpeed);
            Assert.True(unit.IsAlive);
        }

        [Fact]
        public void Id_IsAutoGenerated()
        {
            var def = new UnitDef();
            var u1 = new Unit(def);
            var u2 = new Unit(def);
            Assert.NotEqual(u1.Id, u2.Id);
        }

        [Fact]
        public void Update_NoTarget_DoesNothing()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(50, 50) };
            unit.Update(1f);
            Assert.Equal(new Vector2(50, 50), unit.WorldPosition);
        }

        [Fact]
        public void Update_MovesTowardTarget()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(100, 0);
            unit.Update(0.5f); // 50 pixels at 100px/s for 0.5s

            Assert.Equal(50f, unit.WorldPosition.X, 3);
            Assert.Equal(0f, unit.WorldPosition.Y, 3);
            Assert.NotNull(unit.MoveTarget); // still has target
        }

        [Fact]
        public void Update_ArrivesAtTarget()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(1.5f, 0); // within 2px
            unit.Update(0.1f);

            Assert.Equal(1.5f, unit.WorldPosition.X, 3);
            Assert.Null(unit.MoveTarget); // arrived, target cleared
        }

        [Fact]
        public void Update_SnapsToTarget_WhenOvershooting()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(10, 0);
            unit.Update(1f); // 100px step > 10px distance

            Assert.Equal(10f, unit.WorldPosition.X, 3);
            Assert.Null(unit.MoveTarget);
        }

        [Fact]
        public void Update_Dead_DoesNotMove()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0), IsAlive = false };
            unit.MoveTarget = new Vector2(100, 0);
            unit.Update(1f);

            Assert.Equal(Vector2.Zero, unit.WorldPosition);
            Assert.NotNull(unit.MoveTarget); // target not cleared
        }

        [Fact]
        public void Update_DiagonalMovement()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(100, 100);
            unit.Update(1f); // moves 100 pixels diagonal

            // Direction should be (100,100)/~141.4 normalized * 100
            Assert.Equal(70.71f, unit.WorldPosition.X, 1);
            Assert.Equal(70.71f, unit.WorldPosition.Y, 1);
        }

        // ---- Phase 2: waypoint following ----

        [Fact]
        public void Update_WithPath_FollowsWaypoints()
        {
            var def = new UnitDef { MoveSpeed = 40f };  // slow enough to not overshoot
            // Place unit at world center of grid (0,0)
            var origin = CoordUtil.IsoToWorldCenter(new IsoCoord(0, 0));
            var unit = new Unit(def) { WorldPosition = origin };

            // Waypoints: (3,0) then (6,0) — far enough apart
            unit.Path = new List<IsoCoord> { new(3, 0), new(6, 0) };
            unit.PathIndex = 0;

            // First update — unit moves toward waypoint 0 but doesn't reach it
            unit.Update(0.1f); // moves only 4px at 40px/s
            Assert.Equal(0, unit.PathIndex); // still heading to first waypoint
            Assert.NotEqual(origin, unit.WorldPosition);

            // Move far enough to reach first waypoint
            var wp0Center = CoordUtil.IsoToWorldCenter(new IsoCoord(3, 0));
            var toWp0 = wp0Center - unit.WorldPosition;
            float distToWp0 = toWp0.Length();
            float timeToReach = distToWp0 / def.MoveSpeed + 0.02f;
            unit.Update(timeToReach);
            Assert.Equal(1, unit.PathIndex); // advanced to second waypoint
        }

        [Fact]
        public void Update_ArrivesAtFinalWaypoint_Stops()
        {
            var def = new UnitDef { MoveSpeed = 200f };
            var origin = CoordUtil.IsoToWorldCenter(new IsoCoord(0, 0));
            var unit = new Unit(def) { WorldPosition = origin };

            unit.Path = new List<IsoCoord> { new(1, 0) };
            unit.PathIndex = 0;

            // Move enough to reach the only waypoint
            unit.Update(1f); // 200px at 200px/s — more than enough for 1 tile (32px half-diag)
            Assert.Equal(1, unit.PathIndex); // path exhausted (PathIndex == Path.Count)
            Assert.Null(unit.MoveTarget);
            Assert.False(unit.IsMoving);
        }

        [Fact]
        public void ClearOrders_ResetsAllState()
        {
            var def = new UnitDef();
            var unit = new Unit(def)
            {
                MoveTarget = new Vector2(100, 100),
                Path = new List<IsoCoord> { new(1, 0), new(2, 0) },
                PathIndex = 1,
            };
            unit.AttackTargetId = 42;

            unit.ClearOrders();

            Assert.Null(unit.MoveTarget);
            Assert.Null(unit.Path);
            Assert.Equal(0, unit.PathIndex);
            Assert.Null(unit.AttackTargetId);
        }
    }
}
