using System.Collections.Generic;
using System.Numerics;
using Xunit;

namespace FNARTS.Core.Tests.Entity
{
    public class UnitTests
    {
        private static UnitDef DefaultDef() => new() { MoveSpeed = 100f };

        [Fact]
        public void Constructor_UsesDefinition()
        {
            var def = new UnitDef { Id = "marine", Name = "Marine", MoveSpeed = 80f };
            var unit = new Unit(def);
            Assert.Same(def, unit.Definition);
            Assert.Equal(80f, unit.MoveSpeed);
            Assert.True(unit.IsAlive);
        }

        [Fact]
        public void Id_IsAutoGenerated()
        {
            var def = new UnitDef();
            var u1 = new Unit(def);
            var u2 = new Unit(def);
            Assert.NotEqual(u1.Id, u2.Id);
        }

        [Fact]
        public void Update_NoTarget_DoesNothing()
        {
            var def = DefaultDef();
            var unit = new Unit(def) { WorldPosition = new Vector2(50, 50) };
            unit.Update(1f);
            Assert.Equal(new Vector2(50, 50), unit.WorldPosition);
        }

        [Fact]
        public void Update_MovesTowardTarget_ConstantSpeed()
        {
            var def = DefaultDef();
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(100, 0);
            unit.Update(0.5f); // 50 px at 100px/s for 0.5s

            Assert.Equal(50f, unit.WorldPosition.X, 3);
            Assert.Equal(0f, unit.WorldPosition.Y, 3);
            Assert.True(unit.IsMoving);
        }

        [Fact]
        public void Update_ArrivesAtTarget()
        {
            var def = DefaultDef();
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(1.5f, 0); // within 2px snap
            unit.Update(0.1f);

            Assert.Equal(1.5f, unit.WorldPosition.X, 3);
            Assert.Null(unit.MoveTarget);
            Assert.False(unit.IsMoving);
        }

        [Fact]
        public void Update_SnapsWhenOvershooting()
        {
            var def = DefaultDef();
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(10, 0);
            unit.Update(1f); // 100px step > 10px distance

            Assert.Equal(10f, unit.WorldPosition.X, 3);
            Assert.Null(unit.MoveTarget);
            Assert.Equal(Vector2.Zero, unit.Velocity);
        }

        [Fact]
        public void Update_Dead_DoesNotMove()
        {
            var def = DefaultDef();
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0), IsAlive = false };
            unit.MoveTarget = new Vector2(100, 0);
            unit.Update(1f);

            Assert.Equal(Vector2.Zero, unit.WorldPosition);
            Assert.NotNull(unit.MoveTarget);
        }

        [Fact]
        public void Update_DiagonalMovement()
        {
            var def = DefaultDef();
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.MoveTarget = new Vector2(100, 100);
            unit.Update(1f); // moves 100 pixels at 45°

            // Direction should be diagonal with equal components
            Assert.Equal(70.71f, unit.WorldPosition.X, 1);
            Assert.Equal(70.71f, unit.WorldPosition.Y, 1);
        }

        // ---- waypoint following ----

        [Fact]
        public void Update_WithPath_FollowsWaypoints()
        {
            var def = new UnitDef { MoveSpeed = 200f };
            var origin = CoordUtil.IsoToWorldCenter(new IsoCoord(0, 0));
            var unit = new Unit(def) { WorldPosition = origin };

            unit.Path = new List<IsoCoord> { new(3, 0), new(6, 0) };
            unit.PathIndex = 0;
            unit.Update(1f); // 200px/s for 1s — plenty to reach wp1 (~107px away)

            Assert.Equal(1, unit.PathIndex);
            Assert.True(unit.IsMoving);
        }

        [Fact]
        public void Update_ArrivesAtFinalWaypoint_Stops()
        {
            var def = new UnitDef { MoveSpeed = 200f };
            var origin = CoordUtil.IsoToWorldCenter(new IsoCoord(0, 0));
            var target = CoordUtil.IsoToWorldCenter(new IsoCoord(1, 0));
            var unit = new Unit(def) { WorldPosition = origin };
            unit.MoveTarget = target;
            unit.Path = new List<IsoCoord> { new(1, 0) };
            unit.PathIndex = 0;
            unit.Update(1f);

            Assert.Null(unit.MoveTarget);
            Assert.Null(unit.Path);
            Assert.False(unit.IsMoving);
        }

        [Fact]
        public void Update_WaypointTurn_HardRedirectsVelocity()
        {
            var def = new UnitDef { MoveSpeed = 100f };
            var origin = CoordUtil.IsoToWorldCenter(new IsoCoord(0, 0));
            var wp1 = CoordUtil.IsoToWorldCenter(new IsoCoord(3, 0));
            var wp2 = CoordUtil.IsoToWorldCenter(new IsoCoord(3, 3));

            var unit = new Unit(def) { WorldPosition = origin };
            unit.Path = new List<IsoCoord> { new(3, 0), new(3, 3) };
            unit.PathIndex = 0;

            // Move frame by frame until we pass the corner
            float dt = 1f / 60f;
            for (int i = 0; i < 300 && unit.PathIndex == 0; i++)
                unit.Update(dt);

            // Should have advanced past the corner
            Assert.Equal(1, unit.PathIndex);
            // Velocity should point toward wp2
            Vector2 expectedDir = Vector2.Normalize(wp2 - wp1);
            float dot = Vector2.Dot(Vector2.Normalize(unit.Velocity), expectedDir);
            Assert.True(dot > 0.99f, $"Velocity {unit.Velocity} should point toward wp2 (expected dir {expectedDir})");
        }

        [Fact]
        public void ClearOrders_ResetsAllState()
        {
            var def = new UnitDef();
            var unit = new Unit(def)
            {
                MoveTarget = new Vector2(100, 100),
                Path = new List<IsoCoord> { new(1, 0), new(2, 0) },
                PathIndex = 1,
                Velocity = new Vector2(50, 0),
            };
            unit.AttackTargetId = 42;

            unit.ClearOrders();

            Assert.Null(unit.MoveTarget);
            Assert.Null(unit.Path);
            Assert.Equal(0, unit.PathIndex);
            Assert.Null(unit.AttackTargetId);
            Assert.Equal(Vector2.Zero, unit.Velocity);
            Assert.Null(unit.ForcedMoveSpeed);
        }

        [Fact]
        public void IsMoving_True_WhenMoving()
        {
            var def = DefaultDef();
            var unit = new Unit(def) { WorldPosition = Vector2.Zero };
            unit.Velocity = new Vector2(5, 0);
            Assert.True(unit.IsMoving);
        }

        [Fact]
        public void ForcedMoveSpeed_LimitsActualSpeed()
        {
            var def = new UnitDef { MoveSpeed = 200f };
            var unit = new Unit(def) { WorldPosition = new Vector2(0, 0) };
            unit.ForcedMoveSpeed = 50f; // slowed down
            unit.MoveTarget = new Vector2(100, 0);
            unit.Update(1f);

            // Should move 50px (forced speed) not 200px (natural speed)
            Assert.Equal(50f, unit.WorldPosition.X, 3);
        }

        [Fact]
        public void IsMoving_False_WhenIdle()
        {
            var def = DefaultDef();
            var unit = new Unit(def) { WorldPosition = Vector2.Zero };
            Assert.False(unit.IsMoving);
        }

        // ── Vehicle turret control ────────────────────────────────────

        [Fact]
        public void Vehicle_Idle_TurretOffsetEasesToZero()
        {
            var unit = new Unit(DefaultDef())
            {
                WorldPosition = Vector2.Zero,
                IsVehicle = true,
                BodyRotation = 0f,
                TurretRotation = 1.0f,
                TurretOffset = 1.0f,
            };

            for (int i = 0; i < 60; i++)
                unit.Update(1f / 60f);

            Assert.Equal(0f, unit.TurretOffset, 3);
            Assert.Equal(unit.BodyRotation, unit.TurretRotation, 3);
        }

        [Fact]
        public void Vehicle_Idle_BodyTurnCarriesTurret_Rigidly()
        {
            var unit = new Unit(DefaultDef())
            {
                WorldPosition = Vector2.Zero,
                IsVehicle = true,
                BodyRotation = 0f,
                TurretRotation = 0f,
                TurretOffset = 0f,
            };
            unit.Update(1f / 60f);

            // Body slewed externally (renderer-independent simulation of a turn)
            unit.BodyRotation = 1.5f;
            unit.Update(1f / 60f);

            // Turret must follow the body without lag (offset stays 0)
            Assert.Equal(0f, unit.TurretOffset, 3);
            Assert.Equal(1.5f, unit.TurretRotation, 3);
        }

        [Fact]
        public void Vehicle_Attacking_CoreDoesNotDriveTurret()
        {
            var unit = new Unit(DefaultDef())
            {
                WorldPosition = Vector2.Zero,
                IsVehicle = true,
                BodyRotation = 0f,
                TurretRotation = 2.0f,
            };
            unit.AttackTargetId = 42;

            unit.Update(1f / 60f);

            // Absolute angle is owned by the Game layer while attacking;
            // Core only mirrors the relative offset for a seamless hand-back.
            Assert.Equal(2.0f, unit.TurretRotation, 3);
            Assert.Equal(2.0f, unit.TurretOffset, 3);
        }

        [Fact]
        public void Vehicle_TargetLost_TurretRecentresWithoutSnap()
        {
            var unit = new Unit(DefaultDef())
            {
                WorldPosition = Vector2.Zero,
                IsVehicle = true,
                BodyRotation = 0f,
                TurretRotation = 2.0f,
            };
            unit.AttackTargetId = 42;
            unit.Update(1f / 60f);      // offset mirrors the aim angle (2.0)
            unit.AttackTargetId = null; // target lost

            unit.Update(1f / 60f);

            // Offset eases toward 0 at a bounded rate — no instant snap
            Assert.True(unit.TurretOffset < 2.0f);
            Assert.True(unit.TurretOffset > 1.0f);
            Assert.Equal(unit.TurretOffset, unit.TurretRotation, 3);
        }
    }
}
